### ISSUE TITLE
None of the shaders working

### ISSUE THREAD

**Issue by A1rf4ce45** [cgytrus/MenuShaders#7] opened 2024-05-17 16:44 UTC
i tried many shaders none of them works, why ?

**Comment by cgytrus** [comment] 2024-05-17 18:28
duplicate of #5

**Comment by cgytrus** [comment] 2024-05-17 18:48
the other issue seems to have been an issue with the shader itself so im reopening this, please attach a log file as well as the shader(s) you are trying to use.

**Comment by cgytrus** [comment] 2024-05-30 14:47
closing due to inactivity

**Closed as completed by cgytrus** 2024-05-30 14:47 UTC
